export const articles = [
    { "title": "Title1",
        "categorie": "accessoires",
        "image": "../assets/images/1.jpg",
        "description": "desc1",
        "price": 18,
        "promo": 4,
        "reference": "ref1",
        "couleur": "blanc",
        "taille": 18
    },
    { "title": "Title2",
        "categorie": "accessoires",
        "image": "../assets/images/2.jpg",
        "description": "desc2",
        "price": 12,
        "promo": 3,
        "reference": "ref2",
        "couleur": "rouge",
        "taille": 4
    },
    { "title": "Title3",
        "categorie": "accessoires",
        "image": "../assets/images/3.jpg",
        "description": "desc3",
        "price": 42,
        "promo": 20,
        "reference": "ref3",
        "couleur": "rouge",
        "taille": 18
    },
    { "title": "Title4",
        "categorie": "accessoires",
        "image": "../assets/images/4.jpg",
        "description": "desc4",
        "price": 120,
        "promo": 100,
        "reference": "ref4",
        "couleur": "blanc",
        "taille": 8
    },
    { "title": "Title5",
        "categorie": "accessoires",
        "image": "../assets/images/5.jpg",
        "description": "desc5",
        "price": 36,
        "promo": 8,
        "reference": "ref5",
        "couleur": "rouge",
        "taille": 18
    },
    { "title": "Title6",
        "categorie": "accessoires",
        "image": "../assets/images/6.jpg",
        "description": "desc6",
        "price": 12,
        "promo": 4,
        "reference": "ref6",
        "couleur": "rouge",
        "taille": 18
    },
    { "title": "Title7",
        "categorie": "accessoires",
        "image": "../assets/images/7.jpg",
        "description": "desc7",
        "price": 122,
        "promo": 110,
        "reference": "ref7",
        "couleur": "rouge",
        "taille": 1
    },
    { "title": "Title8",
        "categorie": "accessoires",
        "image": "../assets/images/8.jpg",
        "description": "desc8",
        "price": 88,
        "promo": 40,
        "reference": "ref8",
        "couleur": "noir",
        "taille": 2
    },
    { "title": "Title9",
        "categorie": "accessoires",
        "image": "../assets/images/9.jpg",
        "description": "desc9",
        "price": 28,
        "promo": 12,
        "reference": "ref9",
        "couleur": "rouge",
        "taille": 11
    },
    { "title": "Title10",
        "categorie": "accessoires",
        "image": "../assets/images/10.jpg",
        "description": "desc10",
        "price": 51,
        "promo": 14,
        "reference": "ref10",
        "couleur": "rouge",
        "taille": 14
    },
    { "title": "Title11",
        "categorie": "accessoires",
        "image": "../assets/images/11.jpg",
        "description": "desc11",
        "price": 91,
        "promo": 49,
        "reference": "ref11",
        "couleur": "blanc",
        "taille": 7
    },
    { "title": "Title12",
        "categorie": "accessoires",
        "image": "../assets/images/12.jpg",
        "description": "desc12",
        "price": 65,
        "promo": 25,
        "reference": "ref12",
        "couleur": "rouge",
        "taille": 5
    },
    { "title": "Title13",
        "categorie": "accessoires",
        "image": "../assets/images/13.jpg",
        "description": "desc13",
        "price": 85,
        "promo": 51,
        "reference": "ref13",
        "couleur": "rouge",
        "taille": 3
    },
    { "title": "Title14",
        "categorie": "accessoires",
        "image": "../assets/images/14.jpg",
        "description": "desc14",
        "price": 94,
        "promo": 74,
        "reference": "ref14",
        "couleur": "noir",
        "taille": 48
    },
    { "title": "Title15",
        "categorie": "accessoires",
        "image": "../assets/images/15.jpg",
        "description": "desc15",
        "price": 75,
        "promo": 50,
        "reference": "ref15",
        "couleur": "rouge",
        "taille": 16
    },
    { "title": "Title16",
        "categorie": "accessoires",
        "image": "../assets/images/16.jpg",
        "description": "desc16",
        "price": 122,
        "promo": 34,
        "reference": "ref16",
        "couleur": "rouge",
        "taille": 12
    },
    { "title": "Title17",
        "categorie": "accessoires",
        "image": "../assets/images/1.jpg",
        "description": "desc17",
        "price": 88,
        "promo": 44,
        "reference": "ref17",
        "couleur": "rouge",
        "taille": 10
    },
    { "title": "Title18",
        "categorie": "accessoires",
        "image": "../assets/images/2.jpg",
        "description": "desc18",
        "price": 116,
        "promo": 58,
        "reference": "ref18",
        "couleur": "bleu",
        "taille": 20
    },
    { "title": "Title19",
        "categorie": "accessoires",
        "image": "../assets/images/3.jpg",
        "description": "desc19",
        "price": 16,
        "promo": 8,
        "reference": "ref19",
        "couleur": "noir",
        "taille": 36
    },
    { "title": "Title20",
        "categorie": "accessoires",
        "image": "../assets/images/4.jpg",
        "description": "desc20",
        "price": 80,
        "promo": 40,
        "reference": "ref20",
        "couleur": "bleu",
        "taille": 21
    },
    { "title": "Title21",
        "categorie": "accessoires",
        "image": "../assets/images/5.jpg",
        "description": "desc21",
        "price": 65,
        "promo": 16,
        "reference": "ref21",
        "couleur": "rouge",
        "taille": 28
    },
    { "title": "Title22",
        "categorie": "accessoires",
        "image": "../assets/images/1.jpg",
        "description": "desc22",
        "price": 46,
        "promo": 23,
        "reference": "ref22",
        "couleur": "bleu",
        "taille": 61
    },
    { "title": "Title23",
        "categorie": "accessoires",
        "image": "../assets/images/8.jpg",
        "description": "desc23",
        "price": 90,
        "promo": 45,
        "reference": "ref23",
        "couleur": "rouge",
        "taille": 68
    },
    { "title": "Title24",
        "categorie": "accessoires",
        "image": "../assets/images/10.jpg",
        "description": "desc24",
        "price": 130,
        "promo": 65,
        "reference": "ref24",
        "couleur": "rouge",
        "taille": 64
    },
    { "title": "Title25",
        "categorie": "accessoires",
        "image": "../assets/images/2.jpg",
        "description": "desc25",
        "price": 70,
        "promo": 35,
        "reference": "ref25",
        "couleur": "rouge",
        "taille": 65
    },
    { "title": "Title26",
        "categorie": "accessoires",
        "image": "../assets/images/1.jpg",
        "description": "desc26",
        "price": 28,
        "promo": 14,
        "reference": "ref26",
        "couleur": "bleu",
        "taille": 34
    },
    { "title": "Title27",
        "categorie": "accessoires",
        "image": "../assets/images/6.jpg",
        "description": "desc27",
        "price": 35,
        "promo": 28,
        "reference": "ref27",
        "couleur": "rouge",
        "taille": 32
    },
    { "title": "Title28",
        "categorie": "accessoires",
        "image": "../assets/images/2.jpg",
        "description": "desc28",
        "price": 58,
        "promo": 28,
        "reference": "ref28",
        "couleur": "bleu",
        "taille": 18
    }
];