export const articles = [
    { "title": "Title1",
        "categorie": "accessoires",
        "image": "../assets/images/1.jpg",
        "description": "desc1",
        "price": 12,
        "promo": 4,
        "reference": "ref1"
    },
    { "title": "Title2",
        "categorie": "accessoires",
        "image": "../assets/images/2.jpg",
        "description": "desc2",
        "price": 12,
        "promo": 4,
        "reference": "ref2"
    },
    { "title": "Title3",
        "categorie": "accessoires",
        "image": "../assets/images/3.jpg",
        "description": "desc3",
        "price": 12,
        "promo": 4,
        "reference": "ref3"
    },
    { "title": "Title4",
        "categorie": "accessoires",
        "image": "../assets/images/4.jpg",
        "description": "desc4",
        "price": 12,
        "promo": 4,
        "reference": "ref4"
    },
    { "title": "Title5",
        "categorie": "accessoires",
        "image": "../assets/images/5.jpg",
        "description": "desc5",
        "price": 12,
        "promo": 4,
        "reference": "ref5"
    },
    { "title": "Title6",
        "categorie": "accessoires",
        "image": "../assets/images/6.jpg",
        "description": "desc6",
        "price": 12,
        "promo": 4,
        "reference": "ref6"
    },
    { "title": "Title7",
        "categorie": "accessoires",
        "image": "../assets/images/7.jpg",
        "description": "desc7",
        "price": 12,
        "promo": 4,
        "reference": "ref7"
    },
    { "title": "Title8",
        "categorie": "accessoires",
        "image": "../assets/images/8.jpg",
        "description": "desc8",
        "price": 12,
        "promo": 4,
        "reference": "ref8"
    },
    { "title": "Title9",
        "categorie": "accessoires",
        "image": "../assets/images/9.jpg",
        "description": "desc9",
        "price": 12,
        "promo": 4,
        "reference": "ref9"
    },
    { "title": "Title10",
        "categorie": "accessoires",
        "image": "../assets/images/10.jpg",
        "description": "desc10",
        "price": 12,
        "promo": 4,
        "reference": "ref10"
    },
    { "title": "Title11",
        "categorie": "accessoires",
        "image": "../assets/images/11.jpg",
        "description": "desc11",
        "price": 12,
        "promo": 4,
        "reference": "ref11"
    },
    { "title": "Title12",
        "categorie": "accessoires",
        "image": "../assets/images/12.jpg",
        "description": "desc12",
        "price": 12,
        "promo": 4,
        "reference": "ref12"
    },
    { "title": "Title13",
        "categorie": "accessoires",
        "image": "../assets/images/13.jpg",
        "description": "desc13",
        "price": 12,
        "promo": 4,
        "reference": "ref13"
    },
    { "title": "Title14",
        "categorie": "accessoires",
        "image": "../assets/images/14.jpg",
        "description": "desc14",
        "price": 12,
        "promo": 4,
        "reference": "ref14"
    },
    { "title": "Title15",
        "categorie": "accessoires",
        "image": "../assets/images/15.jpg",
        "description": "desc15",
        "price": 12,
        "promo": 4,
        "reference": "ref15"
    },
    { "title": "Title16",
        "categorie": "accessoires",
        "image": "../assets/images/16.jpg",
        "description": "desc16",
        "price": 12,
        "promo": 4,
        "reference": "ref16"
    },
    { "title": "Title17",
        "categorie": "accessoires",
        "image": "../assets/images/1.jpg",
        "description": "desc17",
        "price": 12,
        "promo": 4,
        "reference": "ref17"
    },
    { "title": "Title18",
        "categorie": "accessoires",
        "image": "../assets/images/2.jpg",
        "description": "desc18",
        "price": 12,
        "promo": 4,
        "reference": "ref18"
    },
    { "title": "Title19",
        "categorie": "accessoires",
        "image": "../assets/images/3.jpg",
        "description": "desc19",
        "price": 12,
        "promo": 4,
        "reference": "ref19"
    },
    { "title": "Title20",
        "categorie": "accessoires",
        "image": "../assets/images/4.jpg",
        "description": "desc20",
        "price": 12,
        "promo": 4,
        "reference": "ref20"
    },
    { "title": "Title21",
        "categorie": "accessoires",
        "image": "../assets/images/5.jpg",
        "description": "desc21",
        "price": 12,
        "promo": 4,
        "reference": "ref21"
    },
    { "title": "Title22",
        "categorie": "accessoires",
        "image": "../assets/images/1.jpg",
        "description": "desc22",
        "price": 12,
        "promo": 4,
        "reference": "ref22"
    },
    { "title": "Title23",
        "categorie": "accessoires",
        "image": "../assets/images/8.jpg",
        "description": "desc23",
        "price": 12,
        "promo": 4,
        "reference": "ref23"
    },
    { "title": "Title24",
        "categorie": "accessoires",
        "image": "../assets/images/10.jpg",
        "description": "desc24",
        "price": 12,
        "promo": 4,
        "reference": "ref24"
    },
    { "title": "Title25",
        "categorie": "accessoires",
        "image": "../assets/images/2.jpg",
        "description": "desc25",
        "price": 12,
        "promo": 4,
        "reference": "ref25"
    },
    { "title": "Title26",
        "categorie": "accessoires",
        "image": "../assets/images/1.jpg",
        "description": "desc26",
        "price": 12,
        "promo": 4,
        "reference": "ref26"
    },
    { "title": "Title27",
        "categorie": "accessoires",
        "image": "../assets/images/6.jpg",
        "description": "desc27",
        "price": 12,
        "promo": 4,
        "reference": "ref27"
    },
    { "title": "Title28",
        "categorie": "accessoires",
        "image": "../assets/images/2.jpg",
        "description": "desc28",
        "price": 12,
        "promo": 4,
        "reference": "ref28"
    }
];